config/routes.rb
Rails.application.routes.draw do
  namespace :api do
     namespace :v1 do
      resources :customers, :ac_tenants
     end 
  end
end

app/models/ac_tenant.rb
class AcTenant < ApplicationRecord
    belongs_to :customers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :ac_tenants
end

app/controllers/api/v1/ac_tenants_controller.rb
class Api::V1::AcTenantsController < ApplicationController
  before_action :set_ac_tenant, only: [:show, :edit, :update, :destroy]

  # GET /ac_tenants
  # GET /ac_tenants.json
  def index
    @ac_tenants = AcTenant.all
    render json: @ac_tenants
  end

  # GET /ac_tenants/1
  # GET /ac_tenants/1.json
  def show
  end

  # GET /ac_tenants/new
  def new
    @ac_tenant = AcTenant.new
  end

  # GET /ac_tenants/1/edit
  def edit
  end

  # POST /ac_tenants
  # POST /ac_tenants.json
  def create
    @ac_tenant = AcTenant.new(ac_tenant_params)

    respond_to do |format|
      if @ac_tenant.save
        format.html { redirect_to @ac_tenant, notice: 'Ac tenant was successfully created.' }
        format.json { render :show, status: :created, location: @ac_tenant }
      else
        format.html { render :new }
        format.json { render json: @ac_tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ac_tenants/1
  # PATCH/PUT /ac_tenants/1.json
  def update
    respond_to do |format|
      if @ac_tenant.update(ac_tenant_params)
        format.html { redirect_to @ac_tenant, notice: 'Ac tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @ac_tenant }
      else
        format.html { render :edit }
        format.json { render json: @ac_tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ac_tenants/1
  # DELETE /ac_tenants/1.json
  def destroy
    @ac_tenant.destroy
    respond_to do |format|
      format.html { redirect_to ac_tenants_url, notice: 'Ac tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ac_tenant
      @ac_tenant = AcTenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ac_tenant_params
      params.require(:ac_tenant).permit(:name)
    end
end

app/controllers/api/v1/customers_controller.rb
class Api::V1::CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
    render json: @customers
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:fist_name, :last_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/ac_tenants_helper.rb
module AcTenantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/ac_tenants/_form.html.erb
<%= form_with(model: ac_tenant, local: true) do |form| %>
  <% if ac_tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ac_tenant.errors.count, "error") %> prohibited this ac_tenant from being saved:</h2>

      <ul>
        <% ac_tenant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ac_tenants/edit.html.erb
<h1>Editing Ac Tenant</h1>

<%= render 'form', ac_tenant: @ac_tenant %>

<%= link_to 'Show', @ac_tenant %> |
<%= link_to 'Back', ac_tenants_path %>

app/views/ac_tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ac Tenants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ac_tenants.each do |ac_tenant| %>
      <tr>
        <td><%= ac_tenant.name %></td>
        <td><%= link_to 'Show', ac_tenant %></td>
        <td><%= link_to 'Edit', edit_ac_tenant_path(ac_tenant) %></td>
        <td><%= link_to 'Destroy', ac_tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ac Tenant', new_ac_tenant_path %>

app/views/ac_tenants/new.html.erb
<h1>New Ac Tenant</h1>

<%= render 'form', ac_tenant: @ac_tenant %>

<%= link_to 'Back', ac_tenants_path %>

app/views/ac_tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ac_tenant.name %>
</p>

<%= link_to 'Edit', edit_ac_tenant_path(@ac_tenant) %> |
<%= link_to 'Back', ac_tenants_path %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fist_name %>
    <%= form.text_field :fist_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Fist name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fist_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fist name:</strong>
  <%= @customer.fist_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Multitenat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>